kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.listener.azureFile.storageAccountName }}-secret
  namespace: {{ .Release.Namespace }}
data:
  azurestorageaccountname: {{ .Values.listener.azureFile.storageAccountName | b64enc }}
  azurestorageaccountkey: {{ .Values.listener.azureFile.storageAccountKey | b64enc }}
type: Opaque
