apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "listener.fullname" . }}-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: {{ .Values.listener.k8sServiceAccountName }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "listener.fullname" . }}-cluster-role
  apiGroup: rbac.authorization.k8s.io