apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.baseName }}-dep
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.baseName }}-listener
  template:
    metadata:
      labels:
        app: {{ .Values.baseName }}-listener
    spec:
      containers:
      - name: listener
        image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.service.targetPort }}