apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "listener.fullname" . }}-dep
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "listener.fullname" . }}-listener
  template:
    metadata:
      labels:
        app: {{ include "listener.fullname" . }}-listener
    spec:
      containers:
      - name: listener
        image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        volumeMounts:
        - name: azure-file
          mountPath: /mnt/{{ .Values.azureFile.shareName }}
          readOnly: false
      volumes:
        - name: azure-file
          csi:
            driver: file.csi.azure.com
            volumeAttributes:
              shareName: {{ .Values.azureFile.shareName }}
              secretName: {{ .Values.azureFile.storageAccountName }}-secret
              mountOptions: "dir_mode=0777,file_mode=0777,cache=strict,actimeo=30,nosharesock"  # optional