{{ if .Values.listener.serviceBus.useKedaAutoScaler }}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ .Values.listener.serviceBus.kedaTriggerAuthName }}
  namespace: {{ .Release.Namespace }}
spec:
  podIdentity:
    provider: azure-workload # azure | azure-workload
    identityId: {{ .Values.listener.serviceBus.kedaUaiClientId }}
{{ end }}
