{{ if .Values.listener.serviceBus.useKedaAutoScaler }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.listener.serviceBus.kedaK8sServiceAccountName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.listener.serviceBus.kedaUaiClientId }}
{{ end }}
