apiVersion: v1
kind: Service
metadata:
  name: {{ include "listener.fullname" . }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.listener.service.type }}
  ports:
    - port: {{ .Values.listener.service.port }}
      targetPort: {{ .Values.listener.service.targetPort }}
  selector:
    app: {{ include "listener.fullname" . }}-listener