apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.listener.listenerK8sServiceAccountName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.listener.serviceBus.listenerUaiClientId }}
