apiVersion: v1
kind: ServiceAccount
metadata:
  name: listener-service-account
  namespace: {{ .Release.Namespace }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.listener.serviceBus.listenerUaiClientId }}
