apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bases-jet-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: bases-jet
roleRef:
  kind: ClusterRole
  name: bases-jet-cluster-role
  apiGroup: rbac.authorization.k8s.io