apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bases-jet-jobs-role-binding
  namespace: bases-jet
subjects:
- kind: ServiceAccount
  name: default
  namespace: bases-jet
roleRef:
  kind: Role
  name: bases-jet-jobs-role
  apiGroup: rbac.authorization.k8s.io