# Default values for listener.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# The values commented are set with non git checked-in value file. They are required.
# Chart deployment is done with the following command:
# `helm install listener ./helm-chart --namespace bases-jet --create-namespace --values ./helm-chart/values-secret.yaml`

#  repository:

listener:
  replicaCount: 1
  k8sServiceAccountName: listener-service-account
  image:
    name: bases-jet/listenerapi
    tag: dev
  resourcesRequests:
    memory: 512Mi
    cpu: 500m
  nodeSelector:
    key: "kubernetes.azure.com/mode"
    value: "user"
  service:
    type: LoadBalancer
    port: 80
    targetPort: 8080
  # azureFile:
  #   storageAccountName:
  #   storageAccountKey:
  #   shareName:
  # serviceBus:
  #   namespace:
  #   queue:
  #   startMessageProcessor:
  #   listenerUaiClientId:
  #   kedaUaiClientId:

jobs:
  image:
    name: bases-jet/jobworker
    tag: dev
  resourcesRequests:
    memory: 512Mi
    cpu: 500m
  nodeSelector:
    key: "kubernetes.azure.com/mode"
    value: "user"
