# Default values for listener.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  name: bases-jet/listenerapi
  tag: dev
#  repository:

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

# azureFile:
#   storageAccountName:
#   storageAccountKey:
#   shareName: