apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - image: ubuntu
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always

### Use this pod for troubleshooting from within the cluster:
# kubectl apply -f ubuntu-pod.yaml
# kubectl exec -it ubuntu -- /bin/bash
# apt update && apt install curl dnsutils iputils-ping -y
### Test DNS resolution:
# curl -I https://www.microsoft.com